name: dbt_basket_craft
version: '1.0'
profile: dbt_basket_craft

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dbt_basket_craft:
    staging:
      +schema: staging
      +materialized: view
    warehouse:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
